### ISSUE TITLE
最好在release模式下编译`bevy-hikari`依赖

### ISSUE THREAD

**Issue by cryscan** [koerriva/rs-towerdefense#1]
WGPU的Bindless Texture在Debug模式下表现得有些抽象，您会发现一旦模型使用纹理贴图便画不出任何东西。因此，最好在Release模式下编译所有依赖：可在`cargo.toml`添加
```toml
[profile.dev.package."*"]
opt-level = 3
```
